"""Emit the tool reference pages of the documentation site from the spec.

Writes one Markdown page per spec tag under docs/reference/tools/, an index of
every tool, and the SUMMARY.md the site's navigation reads. Each tool gets its
summary, description, price, a parameter table and the spec's first example as
a Python, TypeScript and Rust call. CI re-runs this and fails on drift, like
the client emitters.
"""

from __future__ import annotations

import json
import shutil
from typing import Any

from _spec import ROOT, SPEC, body_schema, credits_line, enum_values, load, resolve

OUT = ROOT / "docs" / "reference" / "tools"
HEADER = "<!-- Generated by emit/emit_docs.py from spec/graphsolve-v1.json. Do not edit. -->\n"


def cell(text: str) -> str:
    """Make text safe for a Markdown table cell."""
    return " ".join(text.split()).replace("|", "\\|")


def type_name(schema: dict[str, Any], comps: dict[str, Any]) -> str:
    target = resolve(schema, comps)
    if enum_values(target) is not None:
        return "string"
    if "anyOf" in target or "oneOf" in target:
        kinds = [
            type_name(s, comps) for s in target.get("anyOf") or target.get("oneOf")
        ]
        return " or ".join(dict.fromkeys(k for k in kinds if k != "null"))
    kind = target.get("type")
    if isinstance(kind, list):
        return " or ".join(k for k in kind if k != "null")
    if kind == "array":
        return f"array of {type_name(target.get('items', {}), comps)}"
    return kind or "object"


def allowed(schema: dict[str, Any], comps: dict[str, Any]) -> str:
    values = enum_values(resolve(schema, comps))
    if not values:
        return ""
    shown = ", ".join(f"`{v}`" for v in values[:12])
    more = f" and {len(values) - 12} more" if len(values) > 12 else ""
    return f" One of {shown}{more}."


def description(schema: dict[str, Any], comps: dict[str, Any]) -> str:
    text = schema.get("description") or resolve(schema, comps).get("description") or ""
    return cell(text)


def parameters(op: dict[str, Any], comps: dict[str, Any]) -> list[str]:
    body = resolve(body_schema(op), comps)
    props = body.get("properties") or {}
    if not props:
        return ["This tool takes no arguments."]
    required = set(body.get("required") or [])
    rows = ["| Name | Type | Required | Description |", "|---|---|---|---|"]
    for name, schema in props.items():
        default = schema.get("default")
        shown_default = (
            f" Default `{json.dumps(default)}`." if default is not None else ""
        )
        rows.append(
            f"| `{name}` | {type_name(schema, comps)} | {'yes' if name in required else 'no'} "
            f"| {description(schema, comps)}{allowed(schema, comps)}{shown_default} |"
        )
    return rows


def first_example(op: dict[str, Any]) -> tuple[str, dict[str, Any]] | None:
    examples = op["requestBody"]["content"]["application/json"].get("examples") or {}
    for name, example in examples.items():
        value = example.get("value")
        if isinstance(value, dict):
            return name, value
    return None


def render(value: Any, python: bool, depth: int = 0) -> str:
    """JSON (or a Python literal) with lists of plain values kept on one line."""
    pad, inner = "    " * depth, "    " * (depth + 1)
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = [
            f"{inner}{json.dumps(k)}: {render(v, python, depth + 1)}"
            for k, v in value.items()
        ]
        return "{\n" + ",\n".join(items) + f"\n{pad}}}"
    if isinstance(value, list):
        if all(not isinstance(v, (dict, list)) for v in value):
            return "[" + ", ".join(render(v, python) for v in value) + "]"
        items = [f"{inner}{render(v, python, depth + 1)}" for v in value]
        return "[\n" + ",\n".join(items) + f"\n{pad}]"
    if python and isinstance(value, bool):
        return "True" if value else "False"
    if python and value is None:
        return "None"
    return json.dumps(value)


def python_call(tool: str, args: dict[str, Any]) -> str:
    if not args:
        return f"response = gs.{tool}()"
    lines = [f"response = gs.{tool}("]
    lines += [f"    {key}={render(value, True, 1)}," for key, value in args.items()]
    lines.append(")")
    return "\n".join(lines)


def example_tabs(tool: str, args: dict[str, Any]) -> list[str]:
    body = render(args, False)
    rust_body = render(args, False, 1)
    python = (
        "from graphsolve import GraphSolve\n\ngs = GraphSolve()\n"
        + python_call(tool, args)
        + '\nprint(response["result"])'
    )
    typescript = (
        'import { GraphSolve } from "@graphsolve/sdk";\n\n'
        "const gs = new GraphSolve();\n"
        f"const response = await gs.{tool}({body});\n"
        "console.log(response.result);"
    )
    rust = (
        "use graphsolve::GraphSolve;\nuse serde_json::json;\n\n"
        "let gs = GraphSolve::new()?;\n"
        f'let response = gs\n    .call("{tool}", &json!({rust_body}))\n    .await?;\n'
        'println!("{:?}", response.result);'
    )
    tabs = {
        "Python": ("python", python),
        "TypeScript": ("ts", typescript),
        "Rust": ("rust", rust),
    }
    out = []
    for label, (lang, code) in tabs.items():
        out.append(f'=== "{label}"\n')
        out.append(f"    ```{lang}")
        out.extend(f"    {line}" if line else "" for line in code.splitlines())
        out.append("    ```\n")
    return out


def tool_section(tool: str, op: dict[str, Any], comps: dict[str, Any]) -> list[str]:
    out = [f"## `{tool}`\n", f"{op.get('summary', '').strip()}\n"]
    extra = (op.get("description") or "").strip()
    if extra and extra != op.get("summary", "").strip():
        out.append(f"{extra}\n")
    out.append(f"**Price:** {credits_line(op['x-graphsolve-credits'])}\n")
    out.append("### Parameters\n")
    out.extend(parameters(op, comps))
    out.append("")
    example = first_example(op)
    if example:
        name, args = example
        out.append(f"### Example: {name}\n")
        out.extend(example_tabs(tool, args))
    return out


def main() -> None:
    ops, comps, version = load()
    tags = {
        t["name"]: t.get("description", t["name"])
        for t in json.loads(SPEC.read_text()).get("tags", [])
    }
    by_tag: dict[str, list[str]] = {}
    for tool, op in ops.items():
        tag = (op.get("tags") or ["other"])[0]
        by_tag.setdefault(tag, []).append(tool)
    order = [t for t in tags if t in by_tag] + sorted(
        t for t in by_tag if t not in tags
    )

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    intro = (
        "Every tool the API offers, generated from the API specification "
        f"(engine {version}). Each tool is `POST /v1/tools/{{name}}`, and each "
        "client has a method of the same name.\n"
    )
    index = [
        HEADER,
        "# Tool reference\n",
        intro,
        "| Tool | Domain | What it does | Price |",
        "|---|---|---|---|",
    ]
    summary = ["- [All tools](index.md)"]
    for tag in order:
        title = tags.get(tag, tag.replace("_", " ").capitalize())
        page = [HEADER, f"# {title}\n"]
        for tool in sorted(by_tag[tag]):
            op = ops[tool]
            page.extend(tool_section(tool, op, comps))
            index.append(
                f"| [`{tool}`]({tag}.md#{tool}) | {cell(title)} | {cell(op.get('summary', ''))} "
                f"| {credits_line(op['x-graphsolve-credits'])} |"
            )
        (OUT / f"{tag}.md").write_text("\n".join(page).rstrip() + "\n")
        summary.append(f"- [{title}]({tag}.md)")
    (OUT / "index.md").write_text("\n".join(index) + "\n")
    (OUT / "SUMMARY.md").write_text("\n".join(summary) + "\n")
    print(f"wrote docs/reference/tools — {len(ops)} tools on {len(order)} pages")


if __name__ == "__main__":
    main()
